<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_form_FORM_ID_form_alter().
 */
function allowed_formats_form_field_config_edit_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\Core\Field\FieldConfigInterface $field */
  $field = $form_state->getFormObject()->getEntity();

  if (in_array($field->getType(), _allowed_formats_field_types())) {

    $options = [];
    foreach (filter_formats() as $format) {
      $options[$format->id()] = $format->label();
    }

    $form['third_party_settings']['allowed_formats'] = [
      '#type' => 'checkboxes',
      '#title' => t('Allowed formats'),
      '#options' => $options,
      '#default_value' => $field->getThirdPartySettings('allowed_formats'),
      '#description' => t('Restrict which text formats are allowed, given the user has the required permissions.')
    ];
  }
}
/**
 * Implements hook_field_widget_form_alter().
 */
function allowed_formats_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  /** @var \Drupal\Core\Field\FieldDefinitionInterface $field_definition */
  /****************************************************************************************/
  //Simpnews theme custom starts
  if ($context['widget'] instanceof \Drupal\text\Plugin\Field\FieldWidget\TextareaWidget) {
    $element['#after_build'][] = '_allowed_formats_remove_textarea_help';
  }
  //Simpnews theme custom ends

  
  $field_definition = $context['items']->getFieldDefinition();

  // Base fields are not configurable.
  if (!$field_definition instanceof FieldConfig) {
    return;
  }

  // We can't use the protected isDefaultValueWidget() method.
  $is_default_value_widget = (bool) $form_state->get('default_value_widget');

  if (in_array($field_definition->getType(), _allowed_formats_field_types()) && !$is_default_value_widget) {
    $field_configuration = $field_definition->getConfig($field_definition->getTargetBundle());
    $allowed_formats_setting = $field_configuration->getThirdPartySettings('allowed_formats');

    if (is_array($allowed_formats_setting)) {
      $allowed_formats = array_filter($allowed_formats_setting);
      if (!empty($allowed_formats)) {
        $element['#allowed_formats'] = $allowed_formats;
      }
    }
  }
}

/**
 * Define what field types we want to modify.
 *
 * @return array
 */
function _allowed_formats_field_types() {
  return ['text', 'text_long', 'text_with_summary'];
}

/***************************************************************************************************/
//simpnews theme custom starts
function _allowed_formats_remove_textarea_help($form_element, FormStateInterface $form_state) {
  if (isset($form_element['format'])) {
    // All this stuff is needed to hide the help text.
    unset($form_element['format']['guidelines']);
    unset($form_element['format']['help']);
    unset($form_element['format']['#type']);
    unset($form_element['format']['#theme_wrappers']);
  }

  return $form_element;
}
//simpnews theme custom ends