context.context.*:
  type: config_entity
  label: 'Context configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    name:
      type: string
      label: 'Name'
    group:
      type: string
      label: 'Group'
    description:
      type: string
      label: 'Description'
    requireAllConditions:
      type: boolean
      label: 'Require All Conditions'
    disabled:
      type: boolean
      label: 'Disabled'
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Condition'
    reactions:
      type: sequence
      label: 'Reactions'
      sequence:
        type: reaction.plugin.[id]
        label: 'Reaction'
    weight:
      type: integer
      label: 'Weight'

condition.plugin.request_path_exclusion:
  type: condition.plugin
  label: 'Request Path Exclusion Condition'
  mapping:
    pages:
      type: string

condition.plugin.view_inclusion:
  type: condition.plugin
  label: 'View Inclusion Condition'
  mapping:
    view_inclusion:
      type: sequence
      label: 'View Inclusion'

reaction.plugin.menu:
  type: reaction.plugin
  mapping:
    menu_items:
      type: sequence
      label: 'Menu items'

reaction.plugin.page_template_suggestions:
  type: reaction.plugin
  mapping:
    suggestions:
      type: text
      label: 'Page template suggestions'

reaction.plugin.regions:
  type: reaction.plugin
  mapping:
    regions:
      type: array
      label: 'Regions'

reaction.plugin.theme:
  type: reaction.plugin
  mapping:
    theme:
      type: string
      label: 'Theme'

reaction.plugin.blocks:
  type: reaction.plugin
  mapping:
    theme:
      type: string
      label: 'The theme in which to display the block'
    include_default_blocks:
      type: integer
      label: 'Include blocks from Block layout'
    saved:
      type: boolean
      label: 'Saved'

reaction.plugin.body_class:
  type: reaction.plugin
  mapping:
    body_class:
      type: string
      label: 'The class to add to the body'

reaction.plugin.page_title:
  type: reaction.plugin
  mapping:
    page_title:
      type: string
      label: 'The title to add to the page'
