# Schema for the configuration files of the shortcutperrole module.
shortcutperrole.settings:
  type: config_object
  label: 'Shortcut per Role settings'
  mapping:
    role:
      type: sequence
      label: 'Shortcut set default roles'
      sequence:
        type: string
        label: 'Shortcut set default role'
